# Auto-generated by julia/sheba_ultra.jl
# Zero baseline + ultraspherical series (ultra-only)

const SHEBA_A = 0.0
const SHEBA_B = 0.0
const SHEBA_ALPHA_XI = 1.7427953628298036
const SHEBA_LAMBDA_STAR = 0.25
const SHEBA_NMAX = 6
const SHEBA_COEFFS = [1.3185223804715362, 3.460085956728704, 2.8806009805544757, 0.8943489402886594, 1.0953766211607543, 1.018548120765397, 0.6702198204626669]

phi_baseline_export(zeta) = 0.0
xi_sheba(zeta) = tanh(SHEBA_ALPHA_XI * log1p(max(zeta, -0.999)))

function gegenbauer_export(n, lam, x)
    n == 0 && return 1.0
    n == 1 && return 2.0*lam*x
    c0, c1 = 1.0, 2.0*lam*x
    for k in 1:(n-1)
        c0, c1 = c1, (2*(k+lam)*x*c1 - (k+2lam-1)*c0)/(k+1)
    end
    return c1
end

function ultra_correction_sheba(zeta)
    xi = xi_sheba(zeta)
    sum(SHEBA_COEFFS[n+1] * gegenbauer_export(n, SHEBA_LAMBDA_STAR, xi) for n in 0:SHEBA_NMAX)
end

phi_sheba_ultra(zeta) = phi_baseline_export(zeta) + ultra_correction_sheba(zeta)
