# Auto-generated by julia/sheba_ultra.jl
# Fitted Grachev (2007) baseline + ultraspherical correction

const SHEBA_A = 2.49844027746819
const SHEBA_B = 0.6766125007389536
const SHEBA_ALPHA_XI = 1.7427953628298036
const SHEBA_LAMBDA_STAR = 0.75
const SHEBA_NMAX = 5
const SHEBA_COEFFS = [17.62639820170009, -32.25138311160568, 32.08544081666421, -21.25435028760934, 9.361475163283558, -2.2592738183690266]

phi_baseline_export(zeta) = 1.0 + (SHEBA_A * zeta * max(1.0 + zeta, 1e-8)^(1/3)) / (1.0 + SHEBA_B * zeta)
xi_sheba(zeta) = tanh(SHEBA_ALPHA_XI * log1p(max(zeta, -0.999)))

function gegenbauer_export(n, lam, x)
    n == 0 && return 1.0
    n == 1 && return 2.0*lam*x
    c0, c1 = 1.0, 2.0*lam*x
    for k in 1:(n-1)
        c0, c1 = c1, (2*(k+lam)*x*c1 - (k+2lam-1)*c0)/(k+1)
    end
    return c1
end

function ultra_correction_sheba(zeta)
    xi = xi_sheba(zeta)
    sum(SHEBA_COEFFS[n+1] * gegenbauer_export(n, SHEBA_LAMBDA_STAR, xi) for n in 0:SHEBA_NMAX)
end

phi_sheba_ultra(zeta) = phi_baseline_export(zeta) + ultra_correction_sheba(zeta)
