# Auto-generated by unified_ultra.jl — do not edit by hand
# Unified all-regime ultraspherical φ

const UU_B_U         = 16.0
const UU_LAMBDA_U    = 4.0
const UU_A_S         = 4.0
const UU_B_S         = 1.4271112466347595
const UU_A_XI        = 0.3
const UU_ZETA0       = NaN
const UU_LAMBDA_STAR = 0.25
const UU_NMAX        = 2
const UU_COEFFS      = [-0.5542835877475171, 3.235301100797095, -0.7283405152814774]
const UU_REGIME      = "stable"
const UU_BLEND       = "soft"

phi_u_unified(z) = max(1.0 - UU_B_U*z, 1e-8)^(-1.0/UU_LAMBDA_U)
phi_s_unified(z) = 1.0 + UU_A_S*z*max(1.0+z, 1e-8)^(1/3) / max(1.0+UU_B_S*z, 1e-8)
blend_s_unified(z) = 0.5*(1.0 + tanh(z/0.1))
function phi_base_unified(z)
    s = blend_s_unified(z)
    return (1-s)*phi_u_unified(z) + s*phi_s_unified(z)
end

xi_unified(z) = tanh(UU_A_XI * asinh(z / UU_ZETA0))

function gegenbauer_unified(n, lam, x)
    n == 0 && return 1.0
    n == 1 && return 2.0*lam*x
    c0, c1 = 1.0, 2.0*lam*x
    for k in 1:(n-1)
        c0, c1 = c1, (2*(k+lam)*x*c1 - (k+2lam-1)*c0)/(k+1)
    end
    return c1
end

function ultra_corr_unified(z)
    xi = xi_unified(z)
    return sum(UU_COEFFS[n+1] * gegenbauer_unified(n, UU_LAMBDA_STAR, xi) for n in 0:UU_NMAX)
end

phi_unified(z) = phi_base_unified(z) + ultra_corr_unified(z)
