# Auto-generated by julia/ultraspherical_practical_run.jl
# Fitted MOST + ultraspherical correction model

const ULTRA_A = 1.0
const ULTRA_B = 4.7
const ULTRA_LAMBDA_PROFILE = -1.0
const ULTRA_ALPHA_XI = 1.2751110483723245
const ULTRA_LAMBDA_STAR = 0.25
const ULTRA_NMAX = 6
const ULTRA_COEFFS = [-1.0404372673195514, -7.22625088659016, -5.220756746677391, -1.809620208708425, -1.67863956281399, -2.1206235480975173, -1.0714267811057017]

phi_most_export(zeta) = begin
    base = max(1.0 + ULTRA_B * zeta, 1e-8)
    ULTRA_A * base^(-1.0 / ULTRA_LAMBDA_PROFILE)
end

xi_map_export(zeta) = tanh(ULTRA_ALPHA_XI * zeta)

function gegenbauer_eval_export(n::Int, lambda_star::Float64, x::Float64)
    if n == 0
        return 1.0
    elseif n == 1
        return 2.0 * lambda_star * x
    end
    c_nm1 = 1.0
    c_n = 2.0 * lambda_star * x
    for k in 1:(n - 1)
        c_np1 = (2.0 * (k + lambda_star) * x * c_n - (k + 2.0 * lambda_star - 1.0) * c_nm1) / (k + 1.0)
        c_nm1, c_n = c_n, c_np1
    end
    return c_n
end

function ultra_correction_export(zeta)
    xi = xi_map_export(zeta)
    total = 0.0
    for n in 0:ULTRA_NMAX
        total += ULTRA_COEFFS[n + 1] * gegenbauer_eval_export(n, ULTRA_LAMBDA_STAR, xi)
    end
    return total
end

phi_ultra_export(zeta) = phi_most_export(zeta) + ultra_correction_export(zeta)
